dev

diff --git a/test6377/fileserver/Dockerfile b/test6377/fileserver/Dockerfile
--- a/test6377/fileserver/Dockerfile
+++ b/test6377/fileserver/Dockerfile
@@ -2,22 +2,15 @@ ARG BASE_IMAGE
 
 FROM $BASE_IMAGE
 
-ARG COMMON_SERVICE_PORT
-ARG SERVICE_DIR
-ARG HEALTHCHECK_CMD
-ARG SERVICE_CMD
-ARG USER_NAME
-ARG USER_ID
-ARG SETUP_SCRIPT
+ARG FILESERVER_TASKS
+ARG ENTRY_POINT
 
 COPY tmp /tmp
 
-RUN apk add jq && \
-    chmod -c 755 $SETUP_SCRIPT && \
-    PARAMS='{ "port":'$COMMON_SERVICE_PORT', "serviceDir":"'$SERVICE_DIR'", "healthcheckCmd":"'$HEALTHCHECK_CMD'", "startCmd":"'$SERVICE_CMD'", "userName":"'$USER_NAME'", "userId":'$USER_ID', "dataDir":"/opt/data" }' && \
-    eval "$SETUP_SCRIPT '$PARAMS'" && \
-    rm $SETUP_SCRIPT && \
+RUN . "$FILESERVER_TASKS" \
+    [ "$?" -ne "0" ] && echo "Error 1" && set -e && exit 1 \
+    devon_create_fileserver \
     apk del jq
 
-ENTRYPOINT ["$SERVICE_DIR/$SERVICE_CMD"]
+ENTRYPOINT ["$ENTRY_POINT"]
 
